#!/usr/bin/env python3
"""Refresh the measured-baselines table in the model cards doc.

Reads the baseline condition of allowlisted benchmark runs under a corpus
root and rewrites the generated block between the doc's markers. Models with
no qualifying run are named in a note rather than shown as empty rows. The
corpus is untracked, so this is a local maintainer command, not a CI gate.

Examples:
    # preview the generated table without touching the doc
    python scripts/export_model_baselines.py --stdout

    # rewrite the generated block in docs/model-cards.md
    python scripts/export_model_baselines.py

    # exit 1 if the doc's table is stale
    python scripts/export_model_baselines.py --check
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, NamedTuple

import yaml

REPO = Path(__file__).resolve().parent.parent

BEGIN_MARKER = "<!-- BEGIN GENERATED: baselines -->"
END_MARKER = "<!-- END GENERATED: baselines -->"
EDIT_WARNING = "<!-- Generated by scripts/export_model_baselines.py - do not edit by hand -->"

DEFAULT_RUN_PREFIXES = "piano_only,guitar_only"
BASELINE_CONDITION = "baseline"
UNDEFINED = "—"

METRIC_COLUMNS: tuple[tuple[str, str], ...] = (
    ("onset F1", "note.onset_f1"),
    ("+offset F1", "note.onset_offset_f1"),
    ("+vel F1", "note.onset_offset_velocity_f1"),
    ("vel corr", "expressive.velocity_corr"),
    ("frame F1", "frame.f1"),
)
HEADER = ("Corpus", "Input", "Model", "n", *(label for label, _ in METRIC_COLUMNS))


class Row(NamedTuple):
    dataset: str
    run: str
    input_type: str
    transcriber: str
    n_succeeded: int
    n_files: int
    metrics: dict[str, Any]

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.dataset, self.input_type, self.transcriber)


def _is_within(path: Path, parent: Path) -> bool:
    """True when *path* is *parent* or sits underneath it."""
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _format_metric(value: Any) -> str:
    """Three decimals, or an em dash when the metric is undefined."""
    if value is None:
        return UNDEFINED
    try:
        number = float(value)
    except (TypeError, ValueError):
        return UNDEFINED
    if math.isnan(number):
        return UNDEFINED
    return f"{number:.3f}"


def _format_count(n_succeeded: int, n_files: int) -> str:
    """Bare count, or ``succeeded/total`` when files failed."""
    if n_succeeded == n_files:
        return str(n_succeeded)
    return f"{n_succeeded}/{n_files}"


def _discover(corpus_root: Path) -> Iterator[tuple[str, str, Path]]:
    """Yield ``(dataset, run_name, run_dir)`` for every run holding a summary."""
    for summary_path in sorted(corpus_root.glob("*/benchmark/*/summary.json")):
        run_dir = summary_path.parent
        yield run_dir.parent.parent.name, run_dir.name, run_dir


def _read_input_type(run_dir: Path) -> str | None:
    """Resolved ``render_pipeline.input_type``, or None when unavailable.

    The run directory name is never consulted; only the resolved config is
    authoritative, so a mislabelled directory cannot produce a wrong row.
    """
    config_path = run_dir / "config.yaml"
    if not config_path.exists():
        return None
    try:
        config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return None
    if not isinstance(config, dict):
        return None
    render = config.get("render_pipeline")
    if not isinstance(render, dict):
        return None
    input_type = render.get("input_type")
    return input_type if isinstance(input_type, str) else None


def _baseline_rows(summary_path: Path) -> list[dict[str, Any]]:
    """Baseline-condition entries of a run summary, by exact condition match."""
    try:
        payload = json.loads(summary_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    entries = payload.get("summary") if isinstance(payload, dict) else None
    if not isinstance(entries, list):
        return []
    return [
        entry
        for entry in entries
        if isinstance(entry, dict) and entry.get("condition") == BASELINE_CONDITION
    ]


def _render_table(rows: list[Row]) -> list[str]:
    lines = ["| " + " | ".join(HEADER) + " |", "|" + "---|" * len(HEADER)]
    for row in rows:
        cells = [
            row.dataset,
            row.input_type,
            row.transcriber,
            _format_count(row.n_succeeded, row.n_files),
            *(_format_metric(row.metrics.get(key)) for _, key in METRIC_COLUMNS),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def _render_notes(omitted: dict[str, list[Row]]) -> list[str]:
    lines: list[str] = []
    for transcriber in sorted(omitted):
        where = ", ".join(
            f"`{row.dataset}/{row.run}` (n={row.n_succeeded})" for row in omitted[transcriber]
        )
        lines.append(
            f"_`{transcriber}` is omitted: no qualifying benchmark run. Its only baseline "
            f"data is {where}, too little to compare fairly._"
        )
    return lines


def _render_block(rows: list[Row], omitted: dict[str, list[Row]], newest: float | None) -> str:
    """The full marked block, as a pure function of the run data."""
    stamp = (
        datetime.fromtimestamp(newest, tz=timezone.utc).strftime("%Y-%m-%d")
        if newest is not None
        else "unknown"
    )
    body = [BEGIN_MARKER, EDIT_WARNING, ""]
    body += _render_table(rows)
    notes = _render_notes(omitted)
    if notes:
        body += ["", *notes]
    body += [
        "",
        f"_Baseline condition only, from {len(rows)} run(s) under `corpus/`; newest run "
        f"{stamp}. Each run's own `summary.json` carries its host and timing._",
        END_MARKER,
    ]
    return "\n".join(body)


def _inject(text: str, block: str) -> str | None:
    """Replace the marked region, or None when the markers are unusable."""
    if text.count(BEGIN_MARKER) != 1 or text.count(END_MARKER) != 1:
        return None
    start = text.index(BEGIN_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER)
    if end <= start:
        return None
    return text[:start] + block + text[end:]


def _collect(
    corpus_root: Path, prefixes: tuple[str, ...]
) -> tuple[list[Row], dict[str, list[Row]], float | None, list[str]]:
    """Qualifying rows, omitted transcribers, newest mtime, and warnings."""
    qualifying: list[Row] = []
    seen: list[Row] = []
    newest: float | None = None
    warnings: list[str] = []

    skipped_other = 0

    for dataset, run, run_dir in _discover(corpus_root):
        allowlisted = run.startswith(prefixes)
        input_type = _read_input_type(run_dir)
        if input_type is None:
            # Only an allowlisted run failing here is actionable; the rest are
            # older runs that predate the resolved-config write.
            if allowlisted:
                warnings.append(
                    f"warning: skipping {dataset}/{run}: no readable "
                    f"render_pipeline.input_type in config.yaml"
                )
            else:
                skipped_other += 1
            continue
        summary_path = run_dir / "summary.json"
        entries = _baseline_rows(summary_path)
        if not entries:
            continue
        for entry in entries:
            n_files = int(entry.get("n_files", 0))
            row = Row(
                dataset=dataset,
                run=run,
                input_type=input_type,
                transcriber=str(entry.get("transcriber", "")),
                n_succeeded=int(entry.get("n_succeeded", n_files)),
                n_files=n_files,
                metrics=entry,
            )
            seen.append(row)
            if allowlisted:
                qualifying.append(row)
        if allowlisted:
            mtime = summary_path.stat().st_mtime
            newest = mtime if newest is None else max(newest, mtime)

    if skipped_other:
        warnings.append(
            f"warning: skipped {skipped_other} non-allowlisted run(s) with no "
            f"readable config.yaml"
        )

    qualifying.sort(key=lambda row: row.key)
    covered = {row.transcriber for row in qualifying}
    omitted: dict[str, list[Row]] = {}
    for row in seen:
        if row.transcriber not in covered:
            omitted.setdefault(row.transcriber, []).append(row)
    return qualifying, omitted, newest, warnings


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--corpus-root", type=Path, default=REPO / "corpus")
    parser.add_argument("--doc", type=Path, default=REPO / "docs" / "model-cards.md")
    parser.add_argument(
        "--runs",
        default=DEFAULT_RUN_PREFIXES,
        help="comma-separated run-name prefixes to include",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify only; exit 1 when stale")
    mode.add_argument("--stdout", action="store_true", help="print the block; leave the doc alone")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    corpus_root: Path = args.corpus_root
    doc_path: Path = args.doc

    if not corpus_root.is_dir():
        print(f"error: corpus root not found: {corpus_root}", file=sys.stderr)
        return 1
    if _is_within(doc_path.resolve(), corpus_root.resolve()):
        print(
            f"error: refusing to write {doc_path} inside the corpus root "
            f"({corpus_root}); choose a different --doc",
            file=sys.stderr,
        )
        return 1

    prefixes = tuple(part.strip() for part in args.runs.split(",") if part.strip())
    rows, omitted, newest, warnings = _collect(corpus_root, prefixes)
    for warning in warnings:
        print(warning, file=sys.stderr)

    counts = Counter(row.key for row in rows)
    duplicates = sorted(key for key, count in counts.items() if count > 1)
    if duplicates:
        listed = ", ".join("/".join(key) for key in duplicates)
        print(
            f"error: several allowlisted runs share a row key ({listed}); "
            f"narrow --runs so each row is unambiguous",
            file=sys.stderr,
        )
        return 1

    block = _render_block(rows, omitted, newest)

    if args.stdout:
        print(block)
        return 0

    try:
        current = doc_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: cannot read {doc_path}: {exc}", file=sys.stderr)
        return 1

    updated = _inject(current, block)
    if updated is None:
        print(
            f'error: expected exactly one "{BEGIN_MARKER}" / "{END_MARKER}" pair in '
            f"{doc_path}; add the marker pair under a heading first",
            file=sys.stderr,
        )
        return 1

    if args.check:
        if updated != current:
            print(f"error: {doc_path} is out of date; re-run without --check", file=sys.stderr)
            return 1
        print(f"{doc_path} is up to date ({len(rows)} rows)")
        return 0

    if updated != current:
        try:
            doc_path.write_text(updated, encoding="utf-8")
        except OSError as exc:
            print(f"error: cannot write {doc_path}: {exc}", file=sys.stderr)
            return 1
    print(f"wrote {len(rows)} baseline rows to {doc_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
